### ISSUE TITLE
Compatibility Goals

### ISSUE THREAD

**Issue by Offroaders123** [101arrowz/compression-streams-polyfill#1]
Hi there! I've started using this project to help add compression support to one of my own, and it's worked really well. I was going to see if I could help work on the codebase a little bit, to add a few things like standard exports for `CompressionStream` and `DecompressionStream` for where you only need it to polyfill a section of the Compression Streams API.

My projects that rely on this are running in modern browser and Node versions, so I don't have to worry about things like `TransformStream` and other APIs that may be needed for this to run. The only platform currently a little behind now is Node, as it doesn't support the `deflate-raw` format, while it does support compressing and decompressing for `gzip` and `deflate`. So I wanted to add a feature detection for the polyfill that will also apply it when that is the case, as currently Node won't be polyfilled here because parts of the API are supported with the other two formats.

I was also planning on using this in both WebKit and Gecko platforms, but looks like those have only just recently added support for the full Compression Streams API (wow, yay!). So looks like now this can be the best for older browser versions, and also for Node/old Node versions.

How far back in browser support do you plan for this polyfill to go? I was going to refactor things to use modern syntax to do the feature detection, but then I realized that I probably shouldn't use modern features for a polyfill implementation, haha.

Thanks for making this! It really does help to even out the feature parity across platforms, which allows me to write my libraries with one syntax that essentially works everywhere, with a single build output.

**Comment by Offroaders123** [comment]
Once again, I think I'm going to learn more about the best practices before I recommend changes that don't make sense. But my first thought was to change out the `globalThis`, `self`, and `global` check out to just a single `globalThis` call, as that's been available across most platforms for a few years now. But if this is meant to go back fairly far in terms of support, then that definitely makes sense to include the global scope check.

**Comment by 101arrowz** [comment]
Apologies for the delayed response! This polyfill is intended to work on browsers from as far back as roughly 2015, simply because that's the same level of support that `web-streams-polyfill` offers AFAICT. You're probably right that for most users, `globalThis` alone is enough, but I felt that supporting a few years of extra browsers could be worth the 20 or so bytes that the extra check costs.

**Comment by Offroaders123** [comment]
Oops sorry I left this open so long.
