### ISSUE TITLE
Can't find variable: Worker

### ISSUE THREAD

**Issue by sshrshnv** [101arrowz/compression-streams-polyfill#2]
Can you add an option to select sync/async `fflate` methods to use?
Now a Worker is being created for async methods, and this polyfill breaks when used inside other Worker.

**Comment by bdon** [comment]
+1, I'm running into this as well; I think polyfilling the synchronous methods is a more reliable default.

**Comment by 101arrowz** [comment]
I think the library can decide whether or not to use the synchronous methods by dynamically checking whether or not `Worker` is available. Blocking the main thread by default seems like a bad idea.

**Comment by 101arrowz** [comment]
Fixed in v0.1.5.
